import {
  LayoutDashboard,
  Users,
  Building2,
  UserRound,
  NotebookPen,
  CalendarDays,
  Trophy,
  BellRing,
  BellPlus,
  Banknote,
  Activity,
  Upload,
  BarChart3,
} from "lucide-react";

// Fuente central de navegación
export const MenuItems = [
  {
    title: "Admin Dashboard",
    icon: BarChart3,
    path: "/admin/dashboard",
    roles: ["admin"],
  },
  {
    title: "Dashboard Ludoteca",
    icon: LayoutDashboard,
    path: "/dashboard",
    roles: ["socio", "admin"],
  },
  {
    title: "Mi Rendimiento",
    icon: Activity,
    path: "/dashboard-instructor",
    roles: ["instructor"], 
  },
  {
    title: "Instalaciones",
    icon: Building2,
    path: "/instalaciones",
    roles: ["admin", "recepcion"],
  },
  {
    id: "recepcion",
    title: "Recepción",
    path: "/recepcion",
    icon: BellRing,
    roles: ["recepcion"],
  },
  {
    title: "Socios",
    icon: Users,
    path: "/socios",
    roles: ["admin", "recepcion"],
  },
  {
    title: "Importar Socios",
    icon: Upload,
    path: "/socios/importar",
    roles: ["admin"],
  },
  {
    title: "Dependientes",
    icon: UserRound,
    path: "/dependientes",
    roles: ["admin", "recepcion"],
  },
  {
    title: "Instructores",
    path: "/instructores",
    icon: Users,
    roles: ["admin", "recepcion"],
  },
  {
    title: "Agenda y Reservaciones",
    icon: NotebookPen,
    path: "/actividades",
    roles: ["admin", "recepcion"],
  },
  {
    title: "Sesiones",
    icon: CalendarDays,
    path: "/sesiones",
    roles: ["admin", "recepcion"],
  },
  {
    title: "Mi Calendario",
    icon: CalendarDays,
    path: "/calendario-instructor",
    roles: ["instructor"],
  },
  {
    title: "Torneos",
    icon: Trophy,
    path: "/torneos",
    roles: ["admin", "recepcion"],
  },
  {
    title: "Check-in",
    icon: BellPlus,
    path: "/check-in",
    roles: ["admin", "recepcion", "instructor"],
  },
  {
    title: "Pagos",
    icon: Banknote,
    path: "/pagos",
    roles: [],
  },
];